spring.application.name=ProductService

##Log level
logging.level.org.springframework.web=TRACE

##DB Connection properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/productservicemar26
spring.datasource.username=productservicemar26user
##spring.datasource.password=secret --##No password is defined for our DB